#!/bin/sh
# Build file variants for serving with Apache MultiViews

set -Ceu
# shellcheck disable=2039
[ -n "${BASH-}" ] && set -o pipefail -o posix

if [ $# -ne 2 ] ; then
	echo "Usage: $0 <src> <dst>" >&2
	exit 1
fi

srcdir="${1%/}"
dstdir="${2%/}"

# Convert srcdir/dstdir to absolute physical paths
srcdir=$(cd "$srcdir" && pwd -P)
mkdir -p "$dstdir"
dstdir=$(cd "$dstdir" && pwd -P)

# Copy files in srcdir to dstdir if required
if [ "$dstdir" != "$srcdir" ] ; then
	# Careful about dstdir being inside srcdir
	# Since cp does the recursive traversal, can't exclude deep dstdir
	dstinsrc=${dstdir#"$srcdir/"}
	if [ "$dstinsrc" != "$dstdir" ] || [ "$srcdir" = . ] ; then
		case "$dstinsrc" in
		*/*)
			echo "Error: dst deep inside src not supported." >&2
			exit 1
			;;
		esac
	else
		dstinsrc=
	fi

	mkdir -p "$dstdir"
	find "$srcdir" -maxdepth 1 \
		-not -name "$srcdir" \
		-not -name '.git*' \
		-not -name "$dstinsrc" \
		-exec cp -a '{}' "$dstdir" \;
fi

# If the website is maintained in git, set file mtime to commit time for
# accurate Last-Modified and If-Modified-Since behavior
if [ -d "$srcdir/.git" ] ; then
	# $GIT_DIR (and --git-dir) apply after -C.  Use absolute path.
	srcdir=$(cd "$srcdir" && pwd -P)
	GIT_DIR="$srcdir/.git" git -C "$dstdir" set-mtime
fi

cd "$dstdir"


find . -name '*.xhtml' | while IFS= read -r file ; do
	if ! [ -e "${file%.xhtml}.html" ] ; then
		xhtmltohtml -m -- "$file"
	fi
done

# Pre-compress common text files
find . \( -iname '*.asc' \
	-o -iname '*.atom' \
	-o -iname '*.css' \
	-o -iname '*.html' \
	-o -iname '*.js' \
	-o -iname '*.json' \
	-o -iname '*.pem' \
	-o -iname '*.rss' \
	-o -iname '*.svg' \
	-o -iname '*.txt' \
	-o -iname '*.vcard' \
	-o -iname '*.vcf' \
	-o -iname '*.xhtml' \
	-o -iname '*.xml' \
	\) -print0 |
	xargs -0r build-multiview
