#!/bin/sh
# build.sh - Build the website

set -eux

# Note:  Set timezone to always generate dates in Mountain Timezone
TZ="America/Denver" jekyll

# Copy files with leading underscore excluded by Jekyll (in programs)
# Currently, only file is one generated by phpdocumentor
find programs -name '_*' | while IFS= read -r FILE; do
    cp -ar -- "$FILE" "_site/$FILE"
done

# Rename blog posts from .html to .xhtml
find _site/bits -name '*.html' | while IFS= read -r FILE; do
    mv -- "$FILE" "${FILE%.html}.xhtml"
done

# Assume vnu.jar is set executable and placed in $PATH if available
if command -v vnu.jar >/dev/null 2>&1 ; then
    # Check that XHTML files are valid XHTML5
    find _site -name '*.xhtml' -print0 | \
        xargs -0 -r vnu.jar --
else
    echo 'Validator.nu command-line client not in $PATH, skipping...' >&2
    echo 'See https://validator.github.io/validator/#usage' >&2

    # Check that XHTML files are valid XML
    find _site -name '*.xhtml' -print0 | \
        xargs -0 -r xmllint --nonet --noout
fi

# Note:  Not checking .html files, which are phpdoc/javadoc

# Generate .html versions of .xhtml pages
find _site -name '*.xhtml' | while IFS= read -r FILE; do
    xsltproc --nodtdattr -o "${FILE%.xhtml}.html" _build/xhtmltohtml.xsl "$FILE"
    # Replace the over-conservative us-ascii charset with utf-8
    perl -pi -e 's/\s*<meta[^>]*http-equiv="Content-Type"[^>]*>\s*/  <meta charset="utf-8" \/>\n/i' -- "${FILE%.xhtml}.html"
done

# Check other XML for well-formedness
find _site -iname '*.atom' -o -iname '*.xml' -print0 | xargs -0 -r xmllint --nonet --noout

# Remove .xhtml extension from URLs in the sitemap
sed -i 's/\.xhtml<\/loc>/<\/loc>/' _site/sitemap.xml
