#!/bin/sh
# build.sh - Build the website

set -ex

# Note:  Set timezone to always generate dates in Mountain Timezone
TZ="America/Denver" jekyll

# Copy files with leading underscore excluded by Jekyll (in programs)
# Currently, only file is one generated by phpdocumentor
for FILE in $(find programs -name '_*') ; do
    cp "$FILE" "_site/$FILE"
done

# Rename blog posts from .html to .xhtml
for FILE in $(find _site/bits -name '*.html') ; do
    mv "$FILE" "${FILE%.html}.xhtml"
done

# Check that XHTML files are DTD valid
find _site -name '*.xhtml' | xargs xmllint --nonet --noout --valid

# Generate .html versions of .xhtml pages
for FILE in $(find _site -name '*.xhtml') ; do
    xsltproc --nodtdattr -o "${FILE%.xhtml}.html" _build/xhtmltohtml.xsl "$FILE"
done

# Check other XML for well-formedness
xmllint --nonet --noout $(find _site -iname '*.atom' -o -iname '*.xml')

# Remove .xhtml extension from URLs in the sitemap
sed -i 's/\.xhtml<\/loc>/<\/loc>/' _site/sitemap.xml
